"""
MCP (Model Context Protocol) endpoints (/v1/mcp/*).
"""
import logging
import time
import traceback
from typing import Any, List, Optional, Tuple, Union

from fastapi import APIRouter, Depends, HTTPException, Request, Response
from fastapi.responses import StreamingResponse

from ..auth import verify_api_key
from ..model_store import _INHERIT_ADAPTER, get_store
import json
import uuid
from datetime import datetime

from ..server_schemas import (
    ChatMessage,
    ChatRequest,
    MCPExecuteRequest,
    UsageStats,
    get_server_max_tokens,
)
from ..mcp import get_manager
from ..engine import (
    _build_gen_args,
    _read_tenant_id,
    _split_thinking,
    _count_thinking_tag_tokens,
    suppress_tool_call_content,
    process_tool_calls,
    _infer_reasoning_parser,
)
from ..config import _maybe_clear_cache, get_prefill_step_size
from ..tool_parsers import _infer_tool_parser_from_processor, load_tool_module
from ..prompt_utils import apply_chat_template
from ..reasoning import get_parser as _get_reasoning_parser_cls
from ..generate import normalize_resize_shape, stream_generate

logger = logging.getLogger("xmlx_vlm.routes.mcp")

import asyncio
import os

from ..server_schemas import ChatResponse
from ..memory import get_memory_store
from .completions import chat_completions_endpoint

router = APIRouter()

@router.post("/v1/mcp/execute", response_model=None)
async def mcp_execute_endpoint(request: MCPExecuteRequest, _=Depends(verify_api_key)):
    """Execute MCP tool calls and return results."""
    mcp_manager = get_manager()
    results = await mcp_manager.execute(request.calls)
    return {"results": results}


@router.post("/v1/mcp/chat/completions", response_model=None)
async def mcp_chat_completions_endpoint(request: ChatRequest, http_request: Request, _=Depends(verify_api_key)):
    """
    Chat completions with automatic MCP tool execution.

    Works like /v1/chat/completions but automatically executes any MCP tool
    calls generated by the model and continues the conversation up to 3 rounds.
    Only supports non-streaming mode.
    """
    request.stream = False
    if not getattr(request, "mcp", False):
        # Force mcp on so that tools are injected
        object.__setattr__(request, "mcp", True)

    mcp_manager = get_manager()
    memory_store = get_memory_store()
    max_rounds = int(os.environ.get("MLX_MCP_MAX_ROUNDS", "3"))

    all_messages = list(request.messages)
    total_prompt_tokens = 0
    total_completion_tokens = 0
    total_peak_memory = 0.0

    # Inject relevant memories into system message before first LLM call
    if memory_store and all_messages:
        user_text = ""
        for m in all_messages:
            if m.role == "user" and isinstance(m.content, str):
                user_text = m.content
                break
        if user_text:
            memories = memory_store.search(user_text)
            if memories:
                memory_text = "\n".join(
                    f"- {m['content']}" for m in memories
                )
                sys_prefix = (
                    "The following relevant context from previous conversations "
                    "may help you answer:\n" + memory_text + "\n\n"
                )
                # Inject into existing system message or prepend new one
                if all_messages[0].role in ("system", "developer"):
                    existing = all_messages[0].content or ""
                    all_messages[0] = ChatMessage(
                        role=all_messages[0].role,
                        content=sys_prefix + existing,
                    )
                else:
                    all_messages.insert(
                        0,
                        ChatMessage(role="system", content=sys_prefix),
                    )

    for round_idx in range(max_rounds):
        # Update messages in the request for this round
        request.messages = all_messages

        result = await chat_completions_endpoint(request, http_request)
        if isinstance(result, StreamingResponse):
            return result  # Should not happen because we force stream=False

        choice = result.choices[0]
        msg = choice.message

        total_prompt_tokens += result.usage.prompt_tokens
        total_completion_tokens += result.usage.completion_tokens
        total_peak_memory = max(total_peak_memory, result.usage.peak_memory)

        # Append assistant message
        assistant_msg = ChatMessage(
            role="assistant",
            content=msg.content,
            tool_calls=msg.tool_calls,
            reasoning=msg.reasoning,
        )
        all_messages.append(assistant_msg)

        if not msg.tool_calls:
            break

        # Execute MCP tool calls in parallel
        tool_results = await mcp_manager.execute(msg.tool_calls)
        for tr in tool_results:
            all_messages.append(
                ChatMessage(
                    role="tool",
                    tool_call_id=tr.get("tool_call_id", ""),
                    name=tr.get("name", ""),
                    content=tr.get("content", ""),
                )
            )
    else:
        # Max rounds reached — return what we have
        pass

    # Persist conversation snippets to memory
    if memory_store:
        session_id = getattr(request, "session_id", None) or "default"
        for m in all_messages:
            if m.role == "user" and isinstance(m.content, str) and m.content.strip():
                memory_store.add(session_id, m.content, {"role": "user"})
            elif m.role == "assistant" and isinstance(m.content, str) and m.content.strip():
                memory_store.add(session_id, m.content, {"role": "assistant"})

    # Build final response with accumulated stats
    final_choice = result.choices[0]
    final_choice.message.reasoning = final_choice.message.reasoning
    return ChatResponse(
        id=result.id,
        created=result.created,
        model=result.model,
        usage=UsageStats(
            prompt_tokens=total_prompt_tokens,
            completion_tokens=total_completion_tokens,
            total_tokens=total_prompt_tokens + total_completion_tokens,
            peak_memory=total_peak_memory,
        ),
        choices=[final_choice],
    )


@router.get("/v1/mcp/status", response_model=None)
async def mcp_status_endpoint(_=Depends(verify_api_key)):
    """Get status of all connected external MCP servers."""
    mcp_manager = get_manager()
    return {
        "builtin_tools": len(mcp_manager.schemas) - len(mcp_manager._external_schemas),
        "external_tools": len(mcp_manager._external_schemas),
        "servers": mcp_manager.get_status(),
    }


@router.get("/v1/mcp/tools", response_model=None)
async def mcp_tools_endpoint(_=Depends(verify_api_key)):
    """List all available MCP tools (builtin + external)."""
    mcp_manager = get_manager()
    return {"tools": mcp_manager.schemas}


# ─── Memory endpoints ───────────────────────────────────────────────────────

